# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afb6b259309395d91f7c2fcc0f5cdf409458e8586cb6327ff29f39f12b7f0c9983373703d8633ab9d1d308d3d6459c09f5a69f24160f1514fe7a938cb516c09d

test:
  secret_key_base: f815809f5ba117012e1846e4b9d0664bab769423b3c15349c24612ed87e72ec13e891b157c020e7637e2c629f5ad8351ed60b3b77f21260676e75fce8fe93354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
